workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      # Use a specific Flutter version compatible with the project
      flutter: v2.10.5

      # Use a specific Xcode version for consistency
      xcode: 13.4.1

      # Environment variables for iOS code signing
      groups:
        - ios_code_signing  # Replace with your specific group name

    scripts:
      # Install Flutter dependencies
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      # Build iOS app with --no-sound-null-safety
      - name: Build iOS
        script: |
          flutter build ios --no-sound-null-safety --release

    artifacts:
      # Save the generated IPA file
      - build/ios/ipa/*.ipa

    publishing:
      # Optional: Publish the IPA to App Store Connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
