workflows:
  flutter-ios:
    name: Build Flutter iOS
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.11.3 # Update CocoaPods version
    scripts:
      - name: Clean Flutter Project
        script: flutter clean
      - name: Fetch Dependencies
        script: flutter pub get
      - name: Fix Podfile and Run Pod Install
        script: |
          cd ios
          # Ensure iOS platform is specified
          if [ -f "Podfile" ]; then
            sed -i '' "s/^platform :ios.*/platform :ios, '12.0'/" Podfile || echo "platform :ios, '12.0'" >> Podfile
          else
            echo "platform :ios, '12.0'" > Podfile
          fi
          
          # Check and remove `RunnerTests` references if they exist
          sed -i '' '/target.*RunnerTests/d' Podfile

          # Remove old Pods and Podfile.lock
          rm -rf Pods Podfile.lock

          # Install Pods
          pod install
          cd ..
      - name: Build iOS Release
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa
    publishing:
      scripts:
        - name: Publish Artifacts
          script: echo "Build artifacts published successfully!"
